version: '3'
services:
  frontend:
    container_name: parcel
    build: ./frontend
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
      - frontend_data:/usr/src/frontend/
    depends_on:
      - db
  web:
    container_name: django
    build: ./backend
    command: >
      /bin/sh -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - frontend_data:/usr/src/frontend/
      - ./backend/:/usr/src/starburger/
    ports:
      - '8000:8000'
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - frontend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
volumes:
  postgres_data:
  frontend_data:
