# Generated by Django 3.2.15 on 2023-07-02 20:40

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=50, region=None, verbose_name='Номер телефона')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес доставки')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starburger_orders', to='foodcartapp.customer', verbose_name='Клиент')),
                ('product', models.ManyToManyField(related_name='starburger_orders', to='foodcartapp.Product', verbose_name='Продукты в заказе')),
            ],
        ),
    ]
