# Generated by Django 3.2.15 on 2023-07-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20230719_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Наличными'), ('online', 'Онлайн')], db_index=True, default='cash', max_length=30, verbose_name='Тип оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('incoming', 'Необработанный'), ('in_progress', 'Принят в обработку'), ('delivery', 'Передан курьеру'), ('complete', 'Выполнен')], db_index=True, default='incoming', max_length=30, verbose_name='Статус'),
        ),
    ]
