# Generated by Django 3.2.15 on 2023-08-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230803_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='Комментарий'),
        ),
    ]
