# Generated by Django 3.2.15 on 2023-08-05 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200, verbose_name='Адрес доставки')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('requested_at', models.DateTimeField(default=datetime.datetime(2023, 8, 5, 22, 4, 46, 266367, tzinfo=utc), verbose_name='Дата запроса к геокодеру')),
            ],
        ),
    ]
