# Generated by Django 3.2.15 on 2023-08-06 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geocoder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.TextField(max_length=200, unique=True, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса к геокодеру'),
        ),
    ]
