# Generated by Django 3.2.15 on 2023-07-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_customer_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastname',
        ),
    ]
