# Generated by Django 3.2.15 on 2023-07-03 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20230703_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproductitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starburger_items', to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderproductitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starburger_items', to='foodcartapp.product', verbose_name='продукт'),
        ),
    ]
