# Generated by Django 3.2.15 on 2023-07-09 11:45

from django.db import migrations


def copy_customers_to_orders(apps, schema_editor):
    # Customer = apps.get_model('appname', 'Customer')
    Order = apps.get_model('foodcartapp', 'Order')
    for order in Order.objects.all():
        order.firstname = order.customer.firstname
        order.lastname = order.customer.lastname
        order.phonenumber = order.customer.phonenumber


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_auto_20230704_1227'),
    ]

    operations = [
        migrations.RunPython(copy_customers_to_orders),
    ]
