# Generated by Django 3.2.15 on 2023-07-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230709_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
