# Generated by Django 3.2.15 on 2023-07-15 19:01

from django.db import migrations


def calculate_order_item_price(apps, schema_editor):
    OrderProductItem = apps.get_model('foodcartapp', 'OrderProductItem')
    for item in OrderProductItem.objects.all():
        item.price = item.product.price * item.quantity
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_orderproductitem_price'),
    ]

    operations = [
        migrations.RunPython(calculate_order_item_price)
    ]
