# Generated by Django 3.2.15 on 2023-07-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', max_length=200, verbose_name='Комментарий'),
        ),
    ]
