# Generated by Django 3.2.15 on 2023-08-02 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20230719_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='foodcartapp.restaurant'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('incoming', 'Необработанный'), ('in_progress', 'Готовится'), ('delivery', 'Передан курьеру'), ('complete', 'Выполнен')], db_index=True, default='incoming', max_length=30, verbose_name='Статус'),
        ),
    ]
